### ISSUE TITLE
ODBC transport doesn't work

### ISSUE THREAD

**Issue by kadler** [IBM/python-itoolkit#15]
**[Original report](https://bitbucket.org/litmis/python-itoolkit/issue/15) by John Yeung (Bitbucket: [jky](https://bitbucket.org/jky), GitHub: [jky](https://github.com/jky)).**

----------------------------------------

There are a couple of small fixes needed to bring it up to minimal functionality:

1. On the cursor `execute` (currently line 111 in `iodbccall.py`), `ipc` and `clt` are undefined. They need to be `self.ipc` and `self.ctl`, respectively. (Note the flipping of letters in the latter.)

2. The "rows" being returned are true database rows (as you would expect from PEP 249) so they cannot be directly appended to the XML output string. You have to get the first (and only) element, which is a string, and strip off the nulls (currently line 116):

    xml_out += row[0].rstrip('\x00')

When I made those changes, the simple iCmd example (with RTVJOBA) worked.

**Comment by jkyeung** [comment]
> **[Original report](https://bitbucket.org/litmis/python-itoolkit/issue/15) by John Yeung (Bitbucket: [jky](https://bitbucket.org/jky), GitHub: [jky](https://github.com/jky)).**

Actually, I'm @jkyeung on GitHub. (I couldn't get jky on GitHub, and that link takes you to someone else.)

**Comment by kadler** [comment]
Nope, it's not possible it seems unless we delete the repository and start over:

https://github.com/jeffwidman/bitbucket-issue-migration#additional-notes
> This script is not idempotent--re-running it will leave the first set of imported issues intact, and then create a duplicate set of imported issues after the first set. If you want to re-run the import, it's best to delete your GitHub repo and start over so that the GitHub issue IDs start from 1.

**Comment by kadler** [comment]
With #18 you can now do:

```python
import pyodbc
from itoolkit.transport import DatabaseTransport

conn = pyodbc.connect("DSN=mydsn")
transport = DatabaseTransport(conn)
```

**Comment by jkyeung** [comment]
> Nope, it's not possible it seems unless we delete the repository and start over:

No, don't bother. It sounds like you weren't going to anyway, but just to make it clear, I don't think it's worth the trouble.
