### ISSUE TITLE
Cannot install itoolkit due to iconv.h

### ISSUE THREAD

**Issue by deliego** [IBM/python-itoolkit#26]
Hi,

I've tried installing itoolkit but every time it tries to install it says it cannot build it because it is missing iconv.h
I've installed all sorts of libraries from Visual Studio hoping that the internationalization converter is in it and nothing. I've even gone to lengths of building my own libiconv found here and still nothing:
https://www.codeproject.com/Articles/302012/%2FArticles%2F302012%2FHow-to-Build-libiconv-with-Microsoft-Visual-Studio

Just simply running the "pip install itoolkit" gives me this error:
```
running build_ext
    building 'itoolkit/itoollib' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\itoolkit
    creating build\temp.win-amd64-3.6\Release\itoolkit\lib
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\firstname.lastname\appdata\local\programs\python\python36\include -Ic:\users\firstname.lastname\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -IC:\PROGRA~1\IBM\SQLLIB\INCLUDE -IC:\PROGRA~1\IBM\SQLLIB\LIB "-IC:\Program Files\IBM\MQ\tools\c\include" "-IC:\Program Files\IBM\MQ\tools\cplus\include" /Tcitoolkit/lib/itoollib.c /Fobuild\temp.win-amd64-3.6\Release\itoolkit/lib/itoollib.obj
    itoollib.c
    itoolkit/lib/itoollib.c(16): fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

Am I missing some other dependency to be able to install itoolkit? Has anyone run into this issue before?

Thanks,

Deegz

**Comment by deliego** [comment]
So I just realised, itoolkit is exclusively for IBM i systems and that is why it cannot find any i Series libraries/headers to install. My goal was to run a python script from a Windows machine using itoolkit to gather data from remote IBM i systems.

**Comment by kadler** [comment]
The only thing that requires to be built on IBM i is the DirectTransport/iLibCall, since it calls directly via PASE memory. In the master branch, this code was refactored to be buildable on non-IBM i systems, just giving an error if used. I'm not ready to build a new release yet with that code, since there's other things I want to clean up first, however there was a way to disable building the direct transport with the previous pip: `pip install --global-option=build_ext --global-option='--disable-libcall'  itoolkit`

This works for me on Linux and should work on Windows too, but I haven't tried.

**Comment by deliego** [comment]
Thanks @kadler and @jkyeung . I can return to this project again, I was pulled onto another one for a while.
Yes indeed that both methods mentioned place the itoolkit files in the right location but does not compile the direct.c or ilibcall.c into libraries. I am able to gather some data using pyodbc as suggested but that doesn't give me enough and I have to get data that is only available using commands on those systems and then parsing the data. For this I'll need iLibcall.

@kadler You mentioned it's not ready to be released yet. Do you have a "beta" version or know of a workaround? :)

Thank you so much for all your help, much appreciated!

**Comment by jkyeung** [comment]
On Sun, Feb 10, 2019 at 10:27 PM deliego <notifications@github.com> wrote:

> I am able to gather some data using pyodbc as suggested but that doesn't
> give me enough and I have to get data that is only available using commands
> on those systems and then parsing the data. For this I'll need iLibcall.
>

You misunderstand. Except for (possibly) speed, there is nothing that
iLibCall provides that you can't get from other means. If you can connect
*at all* using pyodbc, that means that itoolkit is **100% fully
functional**.

**Comment by kadler** [comment]
I think @deliego means he is using pyodbc to query the database but he needs to use itoolkit to call programs and commands which cannot be called directly through pyodbc.

Of course you _can_ do this, it's just not documented:
```python
import pyodbc
from itoolkit.db2.idb2call import iDB2Call

transport = iDB2Call(pyodbc.connect('DSN=mydsn'))
...
```

And since all of our examples show using `iLibCall`, it's easy to see how one would come to the assumption that it was required to be able to use itoolkit.

**Comment by deliego** [comment]
Thanks @kadler. Yes, I need to run commands like "DSPSYSSTS" and others to get job info on remote systems, so the code will not be local to the systems.
Does iDB2Call require the XMLSERVICE enabled on those servers?

**Comment by kadler** [comment]
The entire product is built around XMLSERVICE, so yes it needs to be installed and enabled on those servers, but this is done out of the box with any recent IBM i release at sufficient PTF level (look for objects in QXMLSERV library). If you want to use the HTTP transport you'll have to set up the XMLSERVICE CGI handler in an Apache instance, but that's not needed for the Database or any other transports.

**Comment by deliego** [comment]
It works! I'm able to run those commands over my pyodbc conn transport (I really don't know how you do it under the hood, but it works). I didn't have to compile the C libraries either, I was able to use your suggestion of installing it with the --disable-libcall option.

Thanks so much!! :)

**Comment by kadler** [comment]
It just calls an XMLSERVICE stored procedure, nothing too special ;)

Glad you got it working.
