### ISSUE TITLE
Allow iPgm.addParm to pass options to iParm 

### ISSUE THREAD

**Issue by jkyeung** [IBM/python-itoolkit#29]
Right now, you have to import `itoolkit.itoolkit.iParm` separately and jump through some hoops to pass a parameter by value to an ILE procedure, because `addParm` doesn't give you access to any `iParm` options.

I've submitted pull request #28 to address this. (More detailed text is attached to the pull request.)

**Comment by jkyeung** [comment]
Since #28 was accepted and merged, should this issue be closed? Or should we keep it open as a placeholder for the grander plan of a more thorough revamping of the API for calling ILE procedures?

**Comment by kadler** [comment]
Let's just close it.
