### ISSUE TITLE
Cannot escape question mark in CL command (was: Weird behavior trying to escape single-quotes)

### ISSUE THREAD

**Issue by jkyeung** [IBM/python-itoolkit#31]
Sometimes, when trying to issue a CL command with embedded single-quotes, it doesn't work. But sometimes it does. It's probably clearest to illustrate with code:

```python
#! /QOpenSys/pkgs/bin/python3

from itoolkit import iToolKit, iCmd
from itoolkit.db2.idb2call import iDB2Call as DatabaseTransport
# The above line is deprecated and will eventually be:
# from itoolkit.transport import DatabaseTransport

import ibm_db_dbi as db2

conn = db2.connect()
trans = DatabaseTransport(conn)

itool = iToolKit(irow=0)

# No apostrophes - OK
itool.add(iCmd('cmd', "SNDMSG MSG('Hello, everyone!') TOUSR(jyeung)"))
itool.call(trans)
out = itool.dict_out('cmd')
print(out)

itool.clear()

# One apostrophe - OK
itool.add(iCmd('cmd', "SNDMSG MSG('Howdy, y''all!') TOUSR(jyeung)"))
itool.call(trans)
out = itool.dict_out('cmd')
print(out)

itool.clear()

# Two apostrophes - fail
itool.add(iCmd('cmd', "SNDMSG MSG('Howdy, y''all! How ''bout another aposterfee?') TOUSR(jyeung)"))
itool.call(trans)
out = itool.dict_out('cmd')
print(out)

itool.clear()

# Two apostrophes - OK!?
itool.add(iCmd('cmd', "SNDMSG MSG('First: ''; second: ''.') TOUSR(jyeung)"))
itool.call(trans)
out = itool.dict_out('cmd')
print(out)
```

Three of those four work fine. The third and longest one produces an error ('CPF0006', as reported in the 'error1' output dictionary).

All four work from a genuine CL command line.

**Comment by kadler** [comment]
The problem with the third one is the `?` in the command string causing `iCmd` to think it's an output parameter. As a workaround, you can specify the execution mode:

```python
# Two apostrophes - fail
itool.add(iCmd('cmd', "SNDMSG MSG('Howdy, y''all! How ''bout another aposterfee?') TOUSR(jyeung)", {'exec': 'cmd'}))
```

**Comment by jkyeung** [comment]
Interesting. So getting parameters back requires something called 'rexx' mode. Are there any other situations where one might want 'rexx' instead of 'cmd'? And I guess if your suggestion is to use 'cmd' mode, there isn't a way to escape question marks in case one needs both a literal question mark and an output parameter?

**Comment by kadler** [comment]
The only way to dynamically call a CL command with output parameters is to call it via REXX. AFAIK, it's much slower than calling directly, so I would suggest never to use it unless needed.

XMLSERVICE generates a REXX procedure on the fly, calls it, and parses its output. It's not very smart about it, so I suspect that any `?` is interpreted as an output parameter. I could be wrong, though - it's hard to decipher [this mess](https://github.com/IBM/xmlservice/blob/master/src/plugile.rpgle#L960-L1106)

**Comment by jkyeung** [comment]
Well, fortunately, it's a rare CL command indeed which would *require* the ability to accept literal question marks as well as output parameters. Of course it would still be nice to have, but it's very low on my wish list. Closing.

If someone stumbling across this does happen to know a way to specify a literal question mark in 'rexx' mode, by all means, post a comment!
