### ISSUE TITLE
Make PyPI distribution installable via pip on other platforms

### ISSUE THREAD

**Issue by jkyeung** [IBM/python-itoolkit#36]
In issue #26 you mentioned that you have a version of the code which can be built on other platforms (presumably skipping the compilation required for iLibCall). Does that refer to what's proposed in #16?

Regardless, are you ready to release that yet? Or, if it was already slated to be included in 1.6.0, then I can report that it's not working for me on Windows. ;)

You also gave a workaround in #26 that consists of invoking pip with a bunch of optional parameters. Would it be worth documenting that in a more prominent place, until the simpler pip invocation is working?

**Comment by jkyeung** [comment]
Oh, I just tried the verbose pip invocation on my Windows 7 machine at work and it failed to install:

```
C:\Users\jyeung>pip3 install --global-option=build_ext --global-option='--disabl
e-ilibcall' itoolkit
c:\users\jyeung\appdata\local\programs\python\python36\lib\site-packages\pip\_in
ternal\commands\install.py:244: UserWarning: Disabling all use of wheels due to
the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting itoolkit
  Using cached https://files.pythonhosted.org/packages/6c/c7/33e08b2c2e34463e9cd
eae6968c4eb3939e65e892a0f0d94761393290dba/itoolkit-1.6.0.tar.gz
Installing collected packages: itoolkit
  Running setup.py install for itoolkit ... error
    ERROR: Complete output from command 'c:\users\jyeung\appdata\local\programs\
python\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\
\Users\\jyeung\\AppData\\Local\\Temp\\pip-install-c9do1uwf\\itoolkit\\setup.py'"
'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"
'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"
'))' build_ext ''"'"'--disable-ilibcall'"'"'' install --record 'C:\Users\jyeung\
AppData\Local\Temp\pip-record-hsgj66gq\install-record.txt' --single-version-exte
rnally-managed --compile:
    ERROR: c:\users\jyeung\appdata\local\programs\python\python36\lib\distutils\
dist.py:261: UserWarning: Unknown distribution option: 'long_description_content
_type'
      warnings.warn(msg)
    invalid command name ''--disable-ilibcall''
    ----------------------------------------
ERROR: Command "'c:\users\jyeung\appdata\local\programs\python\python36\python.e
xe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jyeung\\AppData\
\Local\\Temp\\pip-install-c9do1uwf\\itoolkit\\setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'
"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext ''"'"'--d
isable-ilibcall'"'"'' install --record 'C:\Users\jyeung\AppData\Local\Temp\pip-r
ecord-hsgj66gq\install-record.txt' --single-version-externally-managed --compile
" failed with error code 1 in C:\Users\jyeung\AppData\Local\Temp\pip-install-c9d
o1uwf\itoolkit\
```

**Comment by kadler** [comment]
A simple `pip install itoolkit` should work - the workaround was removed as it should figure it out automatically now. It works for me on Linux at least, but I have not tested Windows. A compiler is needed to build the dummy extension - perhaps that is the issue?

**Comment by jkyeung** [comment]
> A compiler is needed to build the dummy extension - perhaps that is the issue?

Well, if nothing else, that is certainly *one* issue, since Windows doesn't ship with a compiler. The error message from pip tries to help out, but the link is outdated:

```
    building 'itoolkit/transport/_direct' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    ----------------------------------------
```

Updated links lead to installers for Microsoft's new and gigantic (several gigabytes) ["Build Tools"](https://visualstudio.microsoft.com/visual-cpp-build-tools/), which I've gone ahead and installed. (Note for future readers: As new versions appear, the exact download link changes. You may have to scroll down to find *Build Tools* specifically. As of this writing, [2019](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) is the latest. However, the Build Tools installer seems to be merely the Visual Studio installer with a subset of the components selected, so if you know what you need, you can use any installer.)

Despite reading that the latest version of the compiler should work for building extensions against "newer" versions of Python, I am still unable to get a clean install of itoolkit:

```
    LINK : error LNK2001: unresolved external symbol PyInit_itoolkit/transport/_
direct
    build\temp.win-amd64-3.6\Release\src/itoolkit/transport\_direct.cp36-win_amd
64.lib : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Buil
dTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\link.exe' failed with e
xit status 1120
    ----------------------------------------
```

At this point I don't know if there's some further configuration I need to do to make it work, or if despite what I've read, I really need to use the *exact* same compiler version that was used to build Python (as was traditionally required), or something else.

Isn't there a way to make the PyPI installer either (1) not even attempt binary compilation under certain conditions, or (2) continue gracefully if it fails?

Right now, getting the compilation to work on Windows is more trouble than just extracting the relevant directory from the source bundle and copying it to an appropriate place (thus "installing" the pure-Python parts, which are the only parts that work anyway).

**Comment by kadler** [comment]
So the way it worked before was that setup.py took an option to disable building the iLibCall transport. This was changed to build a stub/empty C extension on non PASE platforms, greatly simplifying things for every platform, except Windows apparently.

In light of this, I think we can solve this better:

1. make the _direct C extension conditionally compiled on non-PASE platforms [here](https://github.com/IBM/python-itoolkit/blob/master/setup.py#L16-L19)
2. Make this always `True` [here](https://github.com/IBM/python-itoolkit/blob/master/src/itoolkit/transport/direct.py#L6) (ie, condition of availability is based on _direct existing/not existing)

**Comment by jkyeung** [comment]
> So the way it worked before was that setup.py took an option to disable building the iLibCall transport. This was changed to build a stub/empty C extension on non PASE platforms, greatly simplifying things for every platform, except Windows apparently.

Right. Supporting Windows is always a pain for Unix/Linux-centric developers, which is approximately all of them. Until Microsoft makes a C/C++ toolchain standard on Windows (which used to be a laughable idea, but like IBM, MS has been moving toward open-source-friendliness), you have to assume that Windows users will generally be unable to compile stuff.

> In light of this, I think we can solve this better:
> 
>     1. make the _direct C extension conditionally compiled on non-PASE platforms [here](https://github.com/IBM/python-itoolkit/blob/master/setup.py#L16-L19)
> 
>     2. Make this always `True` [here](https://github.com/IBM/python-itoolkit/blob/master/src/itoolkit/transport/direct.py#L6) (ie, condition of availability is based on _direct existing/not existing)

All of that is what I thought you already did when you said this (in issue #26):

> In the master branch, this code was refactored to be buildable on non-IBM i systems, just giving an error if used.

As far as I know, it's not customary to have any "dummy" C extensions in Python. From the point of view of the pure-Python code (`direct.py` in this case), there is no advantage to having a C-implemented stub.

**Comment by kadler** [comment]
> As far as I know, it's not customary to have any "dummy" C extensions in Python. From the point of view of the pure-Python code (`direct.py` in this case), there is no advantage to having a C-implemented stub.

Yeah, I'm pretty sure I did that just to make setup.py really clean and simple.

**Comment by kadler** [comment]
This was completed in [version 1.6.2](https://github.com/IBM/python-itoolkit/releases/tag/1.6.2)
