### ISSUE TITLE
Deprectated transports do not work

### ISSUE THREAD

**Issue by kadler** [IBM/python-itoolkit#39]
iRestCall, iDB2Call, and iLibCall do not work, bu t always return `'error': '*NODATA'`.

The problem is caused by refactoring of the code as sub-classes of HttpTransport, DatabaseTransport, and DirectTransport and not returning a value from the sub-classed `call` methods, causing `None` to be returned instead.

**Comment by jkyeung** [comment]
Functions in quite a few languages return the last-evaluated expression in the absence of an explicit `return`. My guess is you slipped into Ruby mode. ;)

**Comment by kadler** [comment]
I actually do not like that behavior, so never did that in Ruby (even if it was idiomatic :man_shrugging:).

I think I was just re-structuring them all at once and making sure to get the `super()` call formatted correctly and working across Python 2/3 that I missed the return.
