### ISSUE TITLE
How to access objects that are in Auxiliary Storage Pool (ASP) ?

### ISSUE THREAD

**Issue by ranga543** [IBM/python-itoolkit#47]
I'm not a RPG developer but we are trying automate some using `ansible` on `IBM I` and we came across an issue to related `Auxiliary Storage Pool`. We have our libraries or programs in `ASP` and we are trying to access them via `itoolkit`. Is it possible to access via `itoolkit` ?

If it's not right place to ask this question, please close the issue.

**Comment by kadler** [comment]
If you call the `SETASPGRP` command as the first action, does that work?

**Comment by ranga543** [comment]
@kadler I didn't try that but If you want I can give it a try.
Is it like `itool.add(iCmd('command', 'SETASPGRP(TEST)'))`

**Comment by kadler** [comment]
Yep, exactly. You'll have to do that at the same time you call your programs as every time you make a call, you'll get a new job.

**Comment by ranga543** [comment]
@kadler I tried below snippet didn't work it's throwing following error `Library X not found for data area`
```
conn = dbi.connect()
    itransport = iDB2Call(conn)
    itool = iToolKit()
    if not asp_group:
        itool.add(iCmd('command', "SETASPGRP({})".format(asp_group), {'error': 'on'}))
    itool.add(iCmd('command', command, {'error': 'on'}))
    itool.call(itransport)
```

**Comment by kadler** [comment]
Looks like the code as written will not call `SETASPGRP` unless none is set. I think you mean:

```python
if asp_group:
  itool.add(iCmd('command', "SETASPGRP({})".format(asp_group), {'error': 'on'}))
```

**Comment by ranga543** [comment]
@kadler sorry we fixed that and we are getting following message
```
```

**Comment by ranga543** [comment]
@kadler any ideas ?

**Comment by kadler** [comment]
My guess is that because it's coming in through a stored procedure and the default is to run in _that_ job instead of using a spawned job, it won't let you run `SETASPGRP`. You could try using the SSH, HTTP, or direct transports which don't have that problem.

**Comment by kadler** [comment]
Though truthfully, I'm not an ASP expert, so I'm not sure if that will work either.

**Comment by kadler** [comment]
Or instead of connecting to `*LOCAL` database, you could use the RDB name for the IASP you want to use.

**Comment by ranga543** [comment]
@kadler It worked when I used DirectTransport. Thank you

**Comment by ranga543** [comment]
@kadler Noticed when we use `DirectTransport` it's not returning actual `command` stand output instead it just shows success but when it's fails it's showing up actual stand error output.
```
{u'success': u'+++ success SETASPGRP ASPGRP(TEST)'}
```
we don't need stand output for this particular command but we have other commands that requires stand output to do some operation based on that.

Is there way to get around the problem ?

**Comment by kadler** [comment]
Do you want the display output? Not sure what you mean by "stand output", but for display output you can use [iCmd5250](https://python-itoolkit.readthedocs.io/en/latest/api.html#itoolkit.iCmd5250).

**Comment by ranga543** [comment]
I tried with `iCmd5250` but it seems to be throwing some kind of error
`test.py`
```
from itoolkit import *
from itoolkit.transport import DirectTransport

itransport = DirectTransport()
itool = iToolKit()
itool.add(iCmd5250('aspgroup_cmd', 'SETASPGRP ASPGRP(TEST)'))
itool.call(itransport)
cmd_out = itool.dict_out('aspgroup_cmd')

if 'error' in cmd_out:
  print ('test')
  print (cmd_out['error'])
  exit()
```
```
{'aspgroup_cmd': {'error': {...}}, u'error1': u" ?xml version='1.0'? xmlservice /sh /xmlservice ", u'error': u'*BADPARSE'}
```

**Comment by kadler** [comment]
Please open a new issue for this.
