### ISSUE TITLE
Run cl command to create a library in an IASP via DirectTransport on a French system failed

### ISSUE THREAD

**Issue by LiJunBJZhu** [IBM/python-itoolkit#62]
* **itoolkit version**:  python3-itoolkit-1.6.1-1.ppc64
* **Python version**:  python3-3.6.10-2.ppc64 
* **OS Name and Version**:  IBM i 7.3 French
* **IBM i version**:  IBMi 7.3 French
* **XMLSERVICE version**:   XML Toolkit 1.9.9.3 

**Describe the bug**

On IBM i French system run a CL command which is to create a library in an iASP fails. The issue doesn't appear on an English system.

command = 'CRTLIB LIB(TRYIASP1) ASP(*ASPDEV) ASPDEV(IASP1)'
itransport = DirectTransport()
itool.add(iCmd(‘command’, command, {‘error’: ‘on’}))
        itool.call(itransport)

"stderr": "iToolKit result dict does not have key 'joblog', the output is {'error': {'error': '*BADPARSE', 'error1': ' ?xml version=\'1.0\'? xmlservice cmd error="on" exec="cmd" var="command" success |¢CDATA¢+++ success QSYS/SETASPGRP ASPGRP(IASP1)!! /success /cmd cmd error="fast" exec="cmd" var="chgjob" success |¢CDATA¢+++ success CHGJOB CCSID(37)!! /success /cmd cmd error="on" exec="cmd" var="command" success |¢CDATA¢+++ success CRTLIB LIB(TRYIASP1) ASP(*ASPDEV) ASPDEV(IASP1)!! /success /cmd /xmlservice ', 'command': {...}}}",

**Comment by kadler** [comment]
Is this still an issue?
