### ISSUE TITLE
PyPI page is outdated

### ISSUE THREAD

**Issue by jkyeung** [IBM/python-itoolkit#65]
Not sure this is the right place to report, but the [PyPI page for itoolkit](https://pypi.org/project/itoolkit/) has some outdated links.

In particular, the [project homepage](https://bitbucket.org/litmis/python-itoolkit) in the left navbar, the [XMLSERVICE project link](https://bitbucket.org/inext/xmlservice-rpg), [samples](https://pypi.org/project/itoolkit/samples/), [contribution guidelines](https://pypi.org/project/itoolkit/CONTRIBUTING.md/), and [license](https://pypi.org/project/itoolkit/LICENSE/).

I think it is definitely good for the project to continue to be listed on PyPI. As such, it's worth keeping that page up to date.

**Comment by kadler** [comment]
Yes, I've noticed this as well. I was working on some changes back in April, but they've languished on my PC. I'll try to get those pushed up soon.

Part of the problem with PyPI is that information there is pulled from the package metadata, so it can't be updated without pushing up a new release. While I could push up a [post-release version](https://www.python.org/dev/peps/pep-0440/#post-releases) I was planning on including this change in a 1.7.0 version, but other things came up.

**Comment by kadler** [comment]
Everything looks good to me on the RC version: https://pypi.org/project/itoolkit/1.7.0rc0/ Once I push the final version, the main https://pypi.org/project/itoolkit page will be updated.

**Comment by kadler** [comment]
With 1.7 now released, the metadata has been corrected.

**Comment by jkyeung** [comment]
The samples, contribution guidelines, and license links all still seem broken on PyPI. They are fine on GitHub.

**Comment by kadler** [comment]
Oh, that's because they use relative links. I opened #69 to address.
