### ISSUE TITLE
Is there a problem with the Japanese environment in iCmd5250 xml output?

### ISSUE THREAD

**Issue by maokit** [IBM/python-itoolkit#67]
* **itoolkit version**: 1.6.1
* **Python version**: 3.6.11
* **OS Name and Version**: IBM i
* **IBM i version**: V7R3M0
* **XMLSERVICE version**: 2.0.2-dev
* ** DSPSYSVAL SYSVAL(QCCSID)** : 5035

**Describe the bug**

Is there a possibility that XML will be corrupted if Japanese is included in the result of iCmd5250?

**The following will result in an error**
Does the output contain Japanese?

```
from itoolkit import *
from itoolkit.transport import DatabaseTransport
import ibm_db_dbi

itool.add(iCmd5250('dspsyssts', 'DSPSYSSTS', {'error': 'on'}))
itool.call(itransport)
dspsyssts = itool.dict_out('dspsyssts')
if 'error' in dspsyssts:
    print(itool.xml_out())
    exit()
else:
    print(dspsyssts['dspsyssts'])
```

**result**

```
<?xml version="1.0" ?><xmlservice>
<error>*BADPARSE</error>
<error><![CDATA[ ?xml version='1.0'? xmlservice sh error="on" var="dspsyssts" ![CDATA[ 1 5770SS1 V7R3M0 160422 SPIKE73 20/10/16 08:54:49 JST CPU % . . . . . . . . . . . . . . : .9 ASP . . . . . . . . . . . . . : 95.45 G CPU % . . . . . . . : .1 ASP % . . . . . . . . . : 45.4769 . . . . . . . . . . . . . . . : 00:00:01 . . . . . . . . . . . . : 95.45 G . . . . . . . . . . : 1381 . . . . . . . . . . . . . : 4885 M % . . . . . . . . . . . . : .007 . . . . . . . . . . . . : 4928 M % . . . . . . . . . . . . : .010 s mw MAX -------DB------- ----- DB----- ACT- WAIT- ACT- b M b M ACT s s WAIT INEL INEL mw e ] 1 679.20 342.25 +++++ .0 .0 .0 .0 54.9 .0 .0 *MACHINE *FIXED 2 4447.21 6.00 121 .0 .0 .0 .0 4344.6 .0 .0 *BASE *FIXED 3 575.97 .00 144 .0 .0 .0 .0 .0 .0 .0 *INTERACT *FIXED 4 57.59 .00 5 .0 .0 .0 .0 .0 .0 .0 *SPOOL *FIXED * * * * * * * * * *]] /sh /xmlservice ]]></error>
</xmlservice>
```

**The following will succeed**
Doesn't Japanese appear in the output?

```
from itoolkit import *
from itoolkit.transport import DatabaseTransport
import ibm_db_dbi

conn = ibm_db_dbi.connect()
itransport = DatabaseTransport(conn)
itool = iToolKit()

itool = iToolKit(iparm=0, iret=0, ids=1, irow=0)
itool.add(iCmd('rtvjoba', 'RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)'))
itool.call(itransport)

rtvjoba = itool.dict_out('rtvjoba')
print (rtvjoba)
if 'error' in rtvjoba:
    print (rtvjoba['error'])
    exit()
else:
    print('USRLIBL = ' + rtvjoba['USRLIBL'])
    print('SYSLIBL = ' + rtvjoba['SYSLIBL'])
    print('CCSID   = ' + rtvjoba['CCSID'])
    print('OUTQ    = ' + rtvjoba['OUTQ'])
```

**result**
```
{'success': '+++ success RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)', 'USRLIBL': 'QGPL       QTEMP', 'SYSLIBL': 'QSYS       QSYS2      QHLPSYS    QUSRSYS', 'CCSID': '5035', 'OUTQ': '*DEV'}
USRLIBL = QGPL       QTEMP
SYSLIBL = QSYS       QSYS2      QHLPSYS    QUSRSYS
CCSID   = 5035
OUTQ    = *DEV
```

**Comment by kadler** [comment]
Can you please enable tracing in the error case and upload the trace file. You can do so by calling `trace_open(file_name)` on the toolkit object before calling it. You'll find the trace file in `/tmp/python_toolkit_<file_name>.log`

**Comment by maokit** [comment]
Thank you!!

I solved it thanks to the hint.
I solved it below.

**1. Setting the PASE LANG environment variable**
`export LANG=JA_JP.UTF-8`

**2. Setting XMLSERVICE control options**
`itransport = DatabaseTransport(conn, ctl="*pase(1208/5035)")`

Send logs when it fails and when it succeeds.
[fails.log](https://github.com/IBM/python-itoolkit/files/5390745/fails.log)
[succeeds.log](https://github.com/IBM/python-itoolkit/files/5390748/succeeds.log)

**Comment by kadler** [comment]
Hi @maokit, sorry I haven't gotten back to this but it sounds like you solved the issue. Is there anything from itoolkit that you need or can we close the issue?
