### ISSUE TITLE
What itoolkit version allows qtemp schema table access using iSqlQuery?

### ISSUE THREAD

**Issue by sgonchigar** [IBM/python-itoolkit#68]
Name: itoolkit                                         
Version: 1.6.1                                         
Summary: IBM i XMLSERVICE toolkit for Python           
Home-page: https://bitbucket.org/litmis/python-itoolkit
Author: IBM                                            
Author-email: UNKNOWN                                  
License: MIT                                           
Location: /QOpenSys/pkgs/lib/python3.6/site-packages   
Requires:                                              

Python 3.6.10
XML Toolkit 2.0.2-dev$
OS Name and Version   V7R3
IBM i version: V7R3

Hello,

Trying to accomplish creating excel spread sheets for qtemp schema objects as shown below and wondering what version of itoolkit allows access to qtemp of the requesting job

def non_qtemp_logic():
	
	conn = db2.connect() 
	cur = conn.cursor() 
	#cur.execute("select * from qiws.qcustcdt") 
	
	sql = "select * from " + sys.argv[1] + "." + sys.argv[2] + " with NC"
	print (sql)
	cur.execute(sql) 
	headers = [descr[0] for descr in cur.description] 
	xlFileName = sys.argv[3] + "/" + sys.argv[4] + ".xlsx"
	print (xlFileName)
	with 	Workbook(xlFileName) as workbook:
		worksheet = workbook.add_worksheet()
		worksheet.write_row('A1', headers)
		for rownum, row in enumerate(cur, start=1):
			worksheet.write_row(rownum, 0, row)	    

if sys.argv[1].lower() == "qtemp":
	qtemp_logic()
else:
	non_qtemp_logic()

**Comment by chrjorgensen** [comment]
QTEMP is scoped to your connection (IBM i job), so your query will find no table in QTEMP except for those created in the same connection.

**Comment by kadler** [comment]
@sgonchigar I don't see any itoolkit code in your example. Is this supposed to be an itoolkit question or an ibm_db question?

**Comment by sgonchigar** [comment]
Thank you for your response. below is the full code. ibm_db works when interactive session job is not referencing qtemp object of the interactive job.

import sys
from xlsxwriter import Workbook 
import ibm_db_dbi as db2 
from itoolkit import *
#from itoolkit.transport import DirectTransport


print (sys.argv[0]) # prints the name of the Python script
print (sys.argv[1]) # prints parameter 1 - Schema Name
print (sys.argv[2]) # prints parameter 2 - Table Name
print (sys.argv[3]) # prints parameter 3 - IFS folder/Path
print (sys.argv[4]) # prints parameter 4 - excel file name


def qtemp_logic():
	print("qtemp_logic, which uses itoolkit")
	
	itool = iToolKit()
	
	sql = "select * from " + sys.argv[1] + "." + sys.argv[2] + " with NC"
	itool.add(iSqlQuery('table_query', sql))
	itool.add(iSqlFetch('table_fetch'))
	itool.add(iSqlFree('table_free'))

	# xmlservice
	itransport = DirectTransport()
#	itransport = iLibCall()
	itransport = itoolkit.transport.DirectTransport
	itool.call(itransport)
	
	cur = itool.dict_out('table_fetch')	
	xlFileName = sys.argv[3] + "/" + sys.argv[4] + ".xlsx"
	print (xlFileName)
	if 'error' in cur:
  		print (cur['error'])
  		exit()
	else:
  		for row in cur['row']:
    			print('row:')
    			print(' USUSER :' + row['USUSER'])
    			print(' USUBOUTQ :' + row['USUBOUTQ'])
    	
  
def non_qtemp_logic():
	
	conn = db2.connect() 
	cur = conn.cursor() 
	#cur.execute("select * from qiws.qcustcdt") 
	
	sql = "select * from " + sys.argv[1] + "." + sys.argv[2] + " with NC"
	print (sql)
	cur.execute(sql) 
	headers = [descr[0] for descr in cur.description] 
	xlFileName = sys.argv[3] + "/" + sys.argv[4] + ".xlsx"
	print (xlFileName)
	with 	Workbook(xlFileName) as workbook:
		worksheet = workbook.add_worksheet()
		worksheet.write_row('A1', headers)
		for rownum, row in enumerate(cur, start=1):
			worksheet.write_row(rownum, 0, row)	    

if sys.argv[1].lower() == "qtemp":
	qtemp_logic()
else:
	non_qtemp_logic()

-----------------------------------
with above code, I get the following error:
qtemp_logic, which uses itoolkit                                             
Traceback (most recent call last):                                           
  File "Converting_DB_table_to_Excel_v2.py", line 71,
 in <module>                                                                 
    qtemp_logic()                                                            
  File "Converting_DB_table_to_Excel_v2.py", line 27,
 in qtemp_logic                                                              
    itransport = DirectTransport()                                           
NameError: name 'DirectTransport' is not defined                             
Press ENTER to end terminal session.

**Comment by sgonchigar** [comment]
> QTEMP is scoped to your connection (IBM i job), so your query will find no table in QTEMP except for those created in the same connection.

Agree. I was trying to see if itoolkit would provide the option to see interactive session job's qtemp.

**Comment by kadler** [comment]
Well, your error about DirectTransport is because you have commented out the import.

If you are trying to access the QTEMP of the job calling this script, none of the solutions will work because Python always runs in a new job.

**Comment by sgonchigar** [comment]
Thank you. That answer's my question.
