### ISSUE TITLE
Improve README links on PyPI

### ISSUE THREAD

**Issue by kadler** [IBM/python-itoolkit#69]
The samples, contribution guidelines, and license links are all relative links. This works great on GitHub, but are broken on PyPI.

For the samples, we could link to readthedocs, but it is nice to have relative links for the others.

**Comment by alanseiden** [comment]
For links that are not samples, should we change (for example):
`CONTRIBUTING.md`
to
`https://github.com/IBM/python-itoolkit/blob/main/CONTRIBUTING.md` 

And for links that ARE samples, should we change:
`samples`
to
`https://python-itoolkit.readthedocs.io/en/latest/examples.html`

?

**Comment by kadler** [comment]
I think that looks right, yeah.

**Comment by alanseiden** [comment]
@kadler Hi, is this update merge-able?
