### ISSUE TITLE
RTVJOBA example works only with CCSID=37

### ISSUE THREAD

**Issue by mikrom-work** [IBM/python-itoolkit#70]
* **itoolkit version**: 
* **Python version**: 3.6.12 running on IBM i
* **OS Name and Version**: 
* **IBM i version**: V7R3
* **XMLSERVICE version**: 

**Describe the bug**
The example from
https://python-itoolkit.readthedocs.io/en/latest/examples.html#calling-the-rtvjoba-cl-command-and-getting-output-parameters
works only when I set on then userprofile (WRKUSRPRF) CCSID = 037

Normally when I have on my userprofile CCSID = 870 the example doesn't work - I get this error:
<pre>
4.4:CSEBK19@~/Python3/itoolkit> python rtvjoba.py

ř▒▒▒@▒▒@▒▒▒▒@▒▒z@ɕ▒▒▒▒▒@▒▒▒▒▒▒▒▒▒@▒▒@▒▒▒▒▒▒▒K{'error': '*** error RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)', 'error1': 'CPF7CFD', 'version': 'XML Toolkit 2.0.2-dev', 'xmlhint': 'RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)', 'xmlhint2': 'RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)', 'jobipc': '*na', 'jobipcskey': 'FFFFFFFF', 'jobname': 'QP0ZSPWP', 'jobuser': 'QSECOFR', 'jobnbr': '506971', 'curuser': 'ROMANAPS', 'ccsid': '870', 'dftccsid': '870', 'paseccsid': '912', 'syslibl': 'QSYS QSYS2 QUSRSYS', 'usrlibl': 'QGPL QTEMP'}
*** error RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)
</pre>

when I change my CCSID of the user profile to 037 then the example works
<pre>
4.4:CSEBK19@~/Python3/itoolkit> python rtvjoba.py
{'success': '+++ success RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)', 'USRLIBL': 'QGPL       QTEMP', 'SYSLIBL': 'QSYS       QSYS2      QUSRSYS', 'CCSID': '37', 'OUTQ': '*DEV'}
USRLIBL = QGPL       QTEMP
SYSLIBL = QSYS       QSYS2      QUSRSYS
CCSID   = 37
OUTQ    = *DEV
</pre>

the Python source code of the example I have used is:
<pre>
# -*- coding: utf-8 -*-

# RTVJOBA can't issue from command line,
# but works with itoolkit
import config
from itoolkit import *

# modify iToolKit not include row node
itool = iToolKit(iparm=0, iret=0, ids=1, irow=0)
itool.add(iCmd('rtvjoba', 'RTVJOBA USRLIBL(?) SYSLIBL(?) CCSID(?N) OUTQ(?)'))

# xmlservice
itool.call(config.itransport)

# output
rtvjoba = itool.dict_out('rtvjoba')
print (rtvjoba)
if 'error' in rtvjoba:
  print (rtvjoba['error'])
  exit()
else:
  print('USRLIBL = ' + rtvjoba['USRLIBL'])
  print('SYSLIBL = ' + rtvjoba['SYSLIBL'])
  print('CCSID   = ' + rtvjoba['CCSID'])
  print('OUTQ    = ' + rtvjoba['OUTQ'])
</pre>

<b>What is wrong ?</b>

**Comment by changlexc** [comment]
xmlservice PTF can fix this issue.
V7R4 SI75969
V7R3 SI75968

**Comment by kadler** [comment]
@mikrom-work did the above PTFs fix the issue for you or is this still broken?

**Comment by alanseiden** [comment]
@kadler Recommend closing issue due to official PTF fix and lack of response from poster.
